### ISSUE TITLE
`v1` tag not updated since `v1.1.0`

### ISSUE THREAD

**Issue by Marukome0743** [docker/scout-action#28]
Currently `v1` tag action doesn't match latest `v1.*.*` action such as `v1.4.1`.
IMO `v1` also syncs with latest `v1.*.*` version like other GitHub actions.

If you did that, I could use just `docker/scout-action@v1` instead of `docker/scout-action@v1.*.*` every updates.

Could you tell me any reasons if `v1` action has to consist in `v1.1.0`?
If there are the reasons, I will use specific version and detect updates through dependabots.
Then feel free to close this issue.

**Comment by cdupuis** [comment]
@Marukome0743 thanks for raising. There's really no reason for the `v1` not to have been updated. This is purely a bug in our release process of the action. Thanks for pointing this out. I have now manually pushed an updated `v1` tag. This should address your issue here.

@eunomie, could you please add this step to the action release process?

**Comment by Marukome0743** [comment]
![QubyQubyStickerGIF](https://github.com/docker/scout-action/assets/146040408/ba81030b-593e-4ec4-8e17-a1d93abe043f)
